### ISSUE TITLE
Push latest to example website + update repo title

### ISSUE THREAD

**Issue by kiwi-josh** [chilicoder/js-repaint-perfs-ember#4]
Expected title: `Js repaint perf implemented in Ember v3.8`
Actual title: `Js repaint perf implemented in Ember v2.10`

http://js-repaint-perf-ember.surge.sh/ <- Still running `v2.10`

**Comment by yarigpopov** [comment]
and what is more important to create PR here
https://github.com/mathieuancelin/js-repaint-perfs/tree/gh-pages/ember

**Comment by yarigpopov** [comment]
I pushed it to http://js-repaint-perf-ember-v3-8.surge.sh/

**Comment by yarigpopov** [comment]
also here is a pr to the main repo
https://github.com/mathieuancelin/js-repaint-perfs/pull/136

**Comment by yarigpopov** [comment]
@wytlytningNZ please check and close
